apiVersion: v1
kind: Service
metadata:
  name: tracking
  namespace: tracking
  labels:
    app: tracking
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 3000
    targetPort: 3000
  selector:
    app: tracking
